task :default do
  rocksdb_dir = File.expand_path('../rocksdb', __FILE__)

  unless File.directory?(rocksdb_dir)
    STDERR.puts "ext/rocksdb missing, please checkout its submodule..."
    exit 1
  end

  # Make sure rocksdb is built...
  sh "cd #{rocksdb_dir} && make librocksdb.so"
end
